Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urlspattern = [
    path('', views.BucketHome.as_view(), name='bucket'),
    path('delete_obj_from_bucket/<path:key>', views.DeleteObjectFromBucketView.as_view(), name='delete_obj_from_bucket'),
    path('download_obj/<path:key>', views.DownloadObjectFromBucketView.as_view(), name='download_obj_from_bucket')
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('products/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urlspattern) ),
    
]

orders/urls.py
from django.urls import path, include
from . import views

app_name = 'orders'


cart_urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add<int:product_id>', views.CartAddView.as_view(), name='cart_item_add'),
    path('remove/<int:product_id>', views.CartItemRemoveView.as_view(), name='cart_item_remove')
]



urlpatterns = [
    path('cart/', include(cart_urlpatterns)),
    path('create/', views.OrderCreateView.as_view(), name='orders_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('pay/<int:order_id>', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrederVerifyView.as_view(), name='order_verify'),
    path('apply_coupon/<int:order_id>', views.CouponApplyView.as_view(), name='apply_coupon')
]

home/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField

class Category(models.Model):
    is_sub_category = models.BooleanField(default=False)
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='sub_categories', blank=True, null=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    def get_absolute_url(self):
        return reverse('home:category_filter', args=[self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category' # the model name used in admin panel
        verbose_name_plural = 'Categories' # to show in admin pannel (plural name use in admin pannel)

    def __str__(self):
        return self.name
    


class Product(models.Model):
    category = models.ManyToManyField(Category,  related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/') # error in removing obj from buckets
    # image = models.ImageField() 
    # needs to pip install pillow

    # description = models.TextField()

    ## How use ckeditor:
    # pip install django-ckeditor
    # add 'ckeditor' in isntalled app in settings.py
    # add | safe in templates
    # to modify add CKEDITOR_CONFIGS in settings.py
    description = RichTextField()




    # price = models.DecimalField(max_digits=4, decimal_places=2) # 1234.12
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Media:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home:product_detail', args=(self.slug,))

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Product, Category
from orders.forms import CartAddForm
from . import tasks
from django.contrib import messages
from utils import IsAdminUserMixin

class HomeView(View):
    template_name = 'home/home.html'

    def get(self, request, *args, **kwargs):
        products = Product.objects.filter(available=True)
        categories = Category.objects.filter(is_sub_category=False)

        if kwargs.get('category_slug'):
            category = Category.objects.get(slug=kwargs['category_slug'])
            products = products.filter(category=category)
        return render(request, self.template_name, {'products': products, 'categories': categories})
        
        

class ProductDetailView(View):
    template_name = 'home/detail.html'
    form_class = CartAddForm

    def get(self, request, slug):
        form = self.form_class
        product = get_object_or_404(Product, slug=slug)
        return render(request, self.template_name, {'product': product, 'form': form})
 




class BucketHome(IsAdminUserMixin, View):
    template_name = 'home/bucket.html'

    # # dispatch method runs befor all methods in class
    # def dispatch(self, request, *args, **kwargs):
    #     if not request.user.is_admin:
    #         return redirect('home:home')
    #     # return super is required if code is continued
    #     return super().dispatch(request, *args, **kwargs)
    # *** dispatch is not required by overwriting the UserPassesTestMixin in utils.py *****

    def get(self, request):
        objects = tasks.all_bucket_objects_task() # is it is asynck use .dealy() or apply_async

        return render(request, self.template_name, {'objects': objects})
    

class DeleteObjectFromBucketView(IsAdminUserMixin, View):
    
    def get(self, request, key):
        delete_result = tasks.delete_object_task.delay(key) # run rabbitmq and run the celery -A Shop worker -l info  in env
        messages.success(request, 'your object will delete soon ...', 'info')
        delete_result.get() # app wait until the result getting, it is not required
        return redirect('home:bucket')
    


class DownloadObjectFromBucketView(IsAdminUserMixin, View):

    def get(self,request, key):
        tasks.download_object_task.delay(key)
        messages.success(request, 'download will stating soon', 'info')
        return redirect('home:bucket')

home/templates/home/bucket.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Size</th>
        <th scope="col">Download</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
        {% for obj in objects%}
            <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ obj.Key }}</td>
            <td>{{ obj.Size|filesizeformat }}</td>
            <td><a href="{% url 'home:download_obj_from_bucket' obj.Key %}">Download</a></td>
            <td><a href="{% url 'home:delete_obj_from_bucket' obj.Key %}">Delete</a></td>
          </tr>
        {% endfor %}


    </tbody>
  </table>
{% endblock content %}

home/templates/home/detail.html
{% extends 'base.html' %}
{% load static %}

{% block extra_headers %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock extra_headers %}

{% block content %}
    <h3>test in detail</h3>
    <h2>{{ product.name }}</h2>
    <small>{{ product.created }}</small>
    <p>{{ product.price }} $</p>
    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="detail-img">
    <p>{{ product.description|safe}}</p>
    <br><br>

    <form action="{% url 'orders:cart_item_add' product.id %}" method="post" novalidate>
        {% csrf_token %}
        {{ form}}
        <input value="add" type="submit">
    </form>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %} 
<!-- load static should be the toppest statement -->
{% block extra_headers %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock extra_headers %}


{% block content %}

    {% for category in categories %}
        <!-- Example split danger button -->
        <div class="btn-group">
            <a class="btn btn-info" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
            <button type="btn btn-info" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="sr-only"></span>
            </button>
            <div class="dropdown-menu">
            {% for sub in category.sub_categories.all %}
                <a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a>
            {% endfor %}

            </div>
        </div>

    {% endfor %}

    <br><br>

    {% for product in products %}
        <div class="card" style="width: 18rem; display:inline-block;">
            <!-- to use media file in debug mode add a code in main urls.py -->
            <img class="card-img-top product-img" src="{{ product.image.url }}" alt="{{ product.name }}"> <!-- url is important after porduct.image.url -->
            <div class="card-body">
            <a class="card-title" href="{{ product.get_absolute_url }}" >{{ product.name }}</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}