Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='user_register'),
    path('verify/', views.UserRegistrationVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),

]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urlspattern = [
    path('', views.BucketHome.as_view(), name='bucket'),
    path('delete_obj_from_bucket/<path:key>', views.DeleteObjectFromBucketView.as_view(), name='delete_obj_from_bucket'),
    path('download_obj/<path:key>', views.DownloadObjectFromBucketView.as_view(), name='download_obj_from_bucket')
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('products/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urlspattern) ),
    
]

orders/urls.py
from django.urls import path, include
from . import views

app_name = 'orders'


cart_urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add<int:product_id>', views.CartAddView.as_view(), name='cart_item_add'),
    path('remove/<int:product_id>', views.CartItemRemoveView.as_view(), name='cart_item_remove')
]



urlpatterns = [
    path('cart/', include(cart_urlpatterns)),
    path('create/', views.OrderCreateView.as_view(), name='orders_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('pay/<int:order_id>', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrederVerifyView.as_view(), name='order_verify'),
    path('apply_coupon/<int:order_id>', views.CouponApplyView.as_view(), name='apply_coupon')
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-dark bg-dark">
    <div style="padding:10px">
      <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
      {% if request.user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'accounts:user_logout' %}">Logout</a>
        <a class="navbar-brand" href="{% url 'orders:cart' %}">CART {{ cart|length }}</a>
        <a class="navbar-brand" style="margin-right: 0px;" href="#">{{ request.user.email }}</a>

      {% else %}
        <a class="navbar-brand" href="{% url 'accounts:user_login' %}">Login</a>
        <a class="navbar-brand" href="{% url 'accounts:user_register' %}">Register</a>
      {% endif %}

      {% if request.user.is_admin %}
        <a class="navbar-brand" style="margin-right: 0px;" href="{% url 'home:bucket' %}">Bucket</a>
      {% endif %}
    </div>
  </nav>